name: SpeckAndTech
title: Speck&Tech
url: http://speckand.tech
kramdown:
  parse_block_html: true
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: "/:year/:month/:title/"
