name: SpeckAndTech
title: Speck&Tech
url: http://speckand.tech
markdown: redcarpet
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: "/:year/:month/:title.html"
